version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      -  mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    expose:
      - "4003"
    ports:
      - "4003:3306"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/nt_back
      - bundle_gems:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db

volumes:
  bundle_gems:
  mysqldata:
    driver: "local"
